### ISSUE TITLE
Resolving components in Rich Text Fields by RichTextResolver impossible due to missing 'data-item-id' attribute

### ISSUE THREAD

**Issue by michalszmyt95** [Kentico/kentico-cloud-js#158]
### Brief bug description

After update kentico-cloud-delivery from 5.3.3 to 5.4.0 I've encountered a problem which caused resolving components by RichTextResolver impossible due to missing 'data-item-id' attribute.

### Repro steps

1. Make model with Rich Text Field in Kentico Cloud
2. Create a Content Item and add a Component to it's Rich Text field (without converting the Component to Content Item)
3. Fetch created Content Item using kentico-cloud-delivery, version greater or equal 5.4.0
4. Use resolveHtml() function from received RichTextField
5. See the error in console: "Error: Parsing HTML failed:Error: HTML node is invalid. Reason: missing 'data-item-id' attribute"

### Screenshots

![image](https://user-images.githubusercontent.com/20721471/55141693-47bd0100-513b-11e9-91a8-31660a939f31.png)

**Comment by Enngage** [comment]
This is related to https://github.com/Kentico/kentico-cloud-js/issues/142 

It's been fixed in `6.0.0-beta.1`, but you can install the latest version [6.0.0-beta.3](https://www.npmjs.com/package/kentico-cloud-delivery/v/6.0.0-beta.2) 

It's still in beta, but should be more stable that all previous releases. There are some breaking changes, but all of them should be fairly simple to fix (e.g. renaming of some methods..). It's still in beta because I'm planning on adding more features and more breaking changes before releasing.
