### ISSUE TITLE
Detecting the types automatically when running queries

### ISSUE THREAD

**Issue by mahpour** [Kentico/kentico-cloud-js#200]
### Motivation

Currently we need to pass the type of the contents twice when we use the Content Delivery client:

```typescript
deliveryClient.items<Movie>()
  .type('movie')
  .orderParameter('elements.title', SortOrder.desc)
  .getObservable()
  .subscribe(response => console.log(response));
```
but we already have a mapping defined when we create the deliveryClient:

```typescript
const deliveryClient = new DeliveryClient({
    projectId: 'xxx',
    typeResolvers: [
        new TypeResolver('movie', () => new Movie()),
    ]
});
``` 

### Proposed solution
`.items<T>()` should get information from the typeresolver and apply it to the rest query. and we shouldn't need to have the `.type('content_type')` call again 

```typescript
deliveryClient.items<Movie>()
  .orderParameter('elements.title', SortOrder.desc)
  .getObservable()
  .subscribe(response => console.log(response));
```

### Additional context

When we use a type safe language like Typescript and we define a mapping in the constructor, we shouldn't use the hardcoded type string in every query. Since type is passed in the first statement it sets the scope of the query and that can resolve the static name of type to be passed to following operator functions.

**Comment by Enngage** [comment]
Hi @mahpour,

Thank you for submitting an issue on our GitHub!

What you are suggesting can and does work in certain languages (C#, Java...), but cannot work with TypeScript as all types are essentially stripped when compiling to JavaScript and this information is not available at runtime. 

In order for this to work you would have to pass constructor so that you would have:

```typescript
deliveryClient.items<Movie>(Movie)
  .type('movie')
  .orderParameter('elements.title', SortOrder.desc)
  .getObservable()
  .subscribe(response => console.log(response));
```
But that kind of beats the purpose and is not really necessary. If you don't want to use `strings` for identifying your types I would recommend using `string enums` such as:

```typescript
enum ContentType {
    Movie = "movie",
    Actor = "actor",
}

deliveryClient.items<Movie>()
  .type(ContentType.Movie)
  .orderParameter('elements.title', SortOrder.desc)
  .getObservable()
  .subscribe(response => console.log(response));
```
Alternatively you could also define type instead of enum:

```tyspescript
type ContentType = 'movie' | 'actor';
```

**Comment by Enngage** [comment]
Closing, but feel free to let us know if you have any further questions.

**Comment by mahpour** [comment]
I reviewed the code for deliveryclient [here](https://github.com/Kentico/kentico-cloud-js/blob/master/packages/delivery/lib/client/delivery-client.ts)

here's the `items` method signature
```typescript
items<TItem extends ContentItem>(): MultipleItemQuery<TItem> {
    return new MultipleItemQuery<TItem>(this.config, this.queryService);
  }
```
`this.config` is referring to the configuration object which holds the type resolver definitions [here](https://github.com/Kentico/kentico-cloud-js/blob/master/packages/delivery/lib/config/delivery-client.config.ts)

```typescript
/**
     * Array of resolvers that are used to create instances of registered classes automatically.
     * If not set, items will be instances of 'ContentItem' class
     */
    typeResolvers?: TypeResolver[];
```


the same mapping configuration data is also available in the `type` method but we are explicitly passing the type in and that can create confusion of the logical type we are passing to `items` method and the name used in `type`. even the proposed solution of using enums will not avoid sdk users from making mistakes. 

we can use typescript `instanceof` or `typeof` operator to find the `TItem` type among the mapping data in `typeResolvers` property of config object at deliveryClient object and use its key to add more to the queries needed in the API.

**Comment by Enngage** [comment]
Yes, that is correct - you may use `instanceof` because the content items are resolved using the type resolvers. However, typeResolver is identifying by `system.type` attribute of each content item and **not by generic type** passed to method - that is not possible to do in TypeScript. 

Passing generic argument to `items` or `item` method is only for your benefit and so that you get intellisense, but it has no other use. For example, following 2 calls will produce **identical** results:

```typescript
deliveryClient.items(Movie)
  .type('movie')
  .orderParameter('elements.title', SortOrder.desc)
  .getObservable()
  .subscribe(response => console.log(response));
```
```typescript
deliveryClient.items<Movie>(Movie)
  .type('movie')
  .orderParameter('elements.title', SortOrder.desc)
  .getObservable()
  .subscribe(response => console.log(response));
```
In many cases the `items` response can contain content items from different types and in this case you could use `ContentItem` generic argument to access common properties (e.g. system, elements...), but you still want those items to be mapped and so `instanceof` will work for each mapped content item.

**Comment by mahpour** [comment]
That makes more sense now. Thanks for clarification. 🙂
