### ISSUE TITLE
Content-type header passed in GET request

### ISSUE THREAD

**Issue by darrencaprani** [Kentico/kentico-cloud-js#210]
The get request coming from the library when I get items from the Kentico Cloud Delivery client is sending a content-type header in GET requests. 

Content-type describes the type of the request body. GET requests don't have a body and therefore it shouldn't have a content-type header.

We use the Kentico Cloud delivery client inside a WAF and every get request is triggering an alarm so please remove it from the get requests coming from the library.

Thanks

**Comment by Enngage** [comment]
Hi, 

I've just checked this and `content-type` request header is not actually being send in Delivery API when the request body is empty. The request headers I get when calling `items()` endpoint are (on the latest beta `6.0.0-beta.10` version)

```
Host: deliver.kenticocloud.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
X-KC-SDKID: npmjs.com;kentico-cloud-delivery;6.0.0-beta.10
Origin: null
Connection: keep-alive
Cache-Control: max-age=0
```
The http client we are using (axios) automatically removes `content-type` header when the body is empty. 

Can you elaborate a bit more on when and where you see the header being sent?

**Comment by darrencaprani** [comment]
We're seeing this when running it from node. Is that from a browser request?

**Comment by Enngage** [comment]
I've released new beta version for delivery `6.0.0-beta.11` (https://www.npmjs.com/package/kentico-cloud-delivery/v/6.0.0-beta.11) which should no longer send `Content-Type` headers under node. 

Could you please try this version and let me know?

**Comment by Enngage** [comment]
Did you had a chance to test this with the new release?

**Comment by darrencaprani** [comment]
I'm using version 5.7.2. When I update to version 6.0.0 there are a lot of breaking change (I guess hence the increase in major version number). Is there any chance to get this change in version 5.7.X?

Thanks,
Darren

**Comment by Enngage** [comment]
Unfortunately I can't do a new release for `5.x.y`, but if I can I would recommend you to give it a try with the `6.0.0-beta.11` as there are not that many changes yet. If I recall correctly, you could fix majority (if not all) issues by replacing

`.getObservable` or `.getPromise` with `.toObservable` or `.toPromise`.

There is also a change in `linkedItems` property so that it is no longer an array, but chances are you are not using this property at all. 

There will be quite a lot new changes in the upcoming release though (as you can probably see in commits already)

**Comment by darrencaprani** [comment]
Unfortunately, the security team in my client will not allow me to use a beta release.

I'll have to wait for the stable release.

I'll add a custom httpService for the time being and remove that default content-type on get requests.

Thanks for your help,
Darren

**Comment by Enngage** [comment]
Ah, okay, thank you for letting me know. 

The only reason it is in beta release is that it contains breaking changes and we have to coordinate release with documentation team & update docs across our portals. Otherwise, the beta version I mentioned is more stable, has some bug fixes from v5 and contains more tests. 

Our plan is to release v6 around the beginning of August.
